### ISSUE TITLE
Update Travis CI job(s) to include vcsim and govc Docker builds

### ISSUE THREAD

**Issue by embano1** [openfaas-incubator/vcenter-connector#15]
As `govmomi` progresses, we should think about updating travis jobs to keep the images and deployments in sync with govmomi, e.g. when new (event) types are added that we can support.

Note: This issue might be resolved when govmomi automatically builds and ships Docker images.

**Comment by alexellis** [comment]
That sounds good :+1:

Shall we try to contribute the Dockerfiles upstream as a single file / image?

Alex

**Comment by embano1** [comment]
Pinged Fabio and Doug from the govmomi team. Will update accordingly.

**Comment by embano1** [comment]
https://github.com/vmware/govmomi/pull/1375
