### ISSUE TITLE
Update connector-dep.yml with OpenFaaS image

### ISSUE THREAD

**Issue by embano1** [openfaas-incubator/vcenter-connector#26]
The current manifest in `yaml/kubernetes/connector-dep.yml` still points to my personal repo. I can easily file a fix for this but saw some inconsistencies with the tags used to build the image.

The repo currently lists tags `0.2.0` and `0.2.1` but Travis tags for the Docker images have a distinct `rc-X` tag. Not sure which one I should use to file a PR or just use `:latest` (which doesn't exist yet in Travis though)?

**Comment by alexellis** [comment]
It is now using 0.4.0
