### ISSUE TITLE
Support request for connector on PKS

### ISSUE THREAD

**Issue by ageoffron** [openfaas-incubator/vcenter-connector#28]
hi,

I deployed openfaas  on PKS.
got embano1/pytag-fn:0.2 to run 
I can connect to the openfaas gui and confirm I have my openfaas-fn pytag-fn deployed.
I deployed the vcenter connector, validated connection to vcenter is ok.

I'm getting a lot fo logs from:
kubectl -n openfaas logs deploy/vcenter-connector -f

it however stops with the following error:
019/10/04 16:38:09 Event [3] &{{{{} 848138955 848138955 2019-10-04 16:38:09.8044 +0000 UTC  0xc0002dd1a0 0xc0002dd1d0 0xc0002dd200 <nil> <nil> <nil> <nil> Alarm 'Host hardware sensor state': an SNMP trap for entity xxx.xxx was sent } {{{{}} Host hardware sensor state} Alarm:alarm-1320}} {{{{}}  xxx.xxx} HostSystem:host-224858}}
2019/10/04 16:38:09 message: {"topic":"alarm.snmp.completed","category":"info","source":"vcenter. xxx.xxx","createdTime":"2019-10-04T16:38:09.8044Z","objectName":"Host hardware sensor state","managedObjectReference":{"Type":"Alarm","Value":"alarm-1320"}}
2019/10/04 16:38:09 Message on topic: alarm.snmp.completed
2019/10/04 16:38:13 invalid character 'i' looking for beginning of value

I understand you may need more logs. just let me know what I can provide to help get root cause.
At this point I'm  not able to

**Comment by alexellis** [comment]
Hi @ageoffron 

It sounds like you haven't configured basic auth properly, the `i` comes from the gateway `invalid credentials`.

> 2019/10/04 16:38:13 invalid character 'i' looking for beginning of value

Alex

**Comment by alexellis** [comment]
/set title: Support request for connector on PKS

**Comment by ageoffron** [comment]
Thank you for your reply. indeed I fixed my issue,  happy to report all is working. Confusion came from where to pull the secret from.

**Comment by alexellis** [comment]
Can you explain what you got wrong please?
